services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: vote-api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: my_db
    ports:
      - "4000:4000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: vote-web
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80" 

  db:
    image: mysql:8.0
    container_name: vote-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  db_data:
